---
- name: ADD COMMON REPOSITORIES  
  yum_repository:
    name: "{{ repos.name }}"
    description: "{{ repos.description }}"
    baseurl: "{{ repos.baseurl }}"
    gpgcheck: "{{ repos.gpgcheck }}"
    gpgkey: "{{ repos.gpgkey }}"
  loop: "{{ group_repos }}"
  loop_control:
    loop_var: repos