---

- include_tasks: get_os_version.yml
- include_tasks: manage_firewall.yml
  tags:
    - firewall

- include_tasks: add_yum_repos.yml
- include_tasks: install_yum_packages.yml

#- include_tasks: install_pip_packages.yml