---
- name: Add host to docker_compose group
  add_host:
    name: "{{ ansible_host }}"
    groups: docker_compose

- name: Include task to install docker_compose
  include_tasks: install_docker_compose.yml
  tags:
    - docker_compose

# - name: Create directory for Docker workspace
#   file:
#     path: /
#     state: directory