---
- name: Include task to install docker_compose
  include_tasks: install_docker_compose.yml
  tags:
    - docker_compose

# - name: Create directory for Docker workspace
#   file:
#     path: /
#     state: directory