---
- name: Enable firewalld
  service:
    name: firewalld
    enabled: yes
  when: enable_firewalld
  tags:
    - firewall

- name: Start firewalld
  service:
    name: firewalld
    state: started
  when: enable_firewalld
  tags:
    - firewall