---

- name: Create {{ docker_iam.docker_group }} group
  group:
    name: "{{ docker_iam.docker_group }}"
    state: present
  tags:
    - docker
    
- name: Create {{ docker_iam.docker_user }} user and add to {{ docker_iam.docker_group }} group
  user:
    name: "{{ docker_iam.docker_user }}"
    group: "{{ docker_iam.docker_group }}"
  tags:
    - docker

- name: Create .ssh directory for {{ docker_iam.docker_user }}
  file:
    path: "/home/{{ docker_iam.docker_user }}/.ssh"
    state: directory
    owner: "{{ docker_iam.docker_user }}"
    group: "{{ docker_iam.docker_group }}"
    mode: 0700
  tags:
    - docker

- name: Generate an OpenSSH rsa keypair
  openssh_keypair:
    path: "/home/{{ docker_iam.docker_user }}/.ssh/id_rsa"
    owner: "{{ docker_iam.docker_user }}"
    group: "{{ docker_iam.docker_group }}"
    state: present
  tags:
    - docker

- name: Get id_rsa.pub
  shell: cat /home/{{ docker_iam.docker_user }}/.ssh/id_rsa.pub
  register: read_id_rsa_pub
  tags:
    - docker

- name: Put id_rsa.pub into authorized_keys
  lineinfile:
    path: "/home/{{ docker_iam.docker_user }}/.ssh/authorized_keys"
    line: "{{ read_id_rsa_pub.stdout }}"
    insertafter: EOF
    owner: "{{ docker_iam.docker_user }}"
    group: "{{ docker_iam.docker_group }}"
    mode: '0600'
    create: yes
    backup: yes
  tags:
    - docker

- name: Get id_rsa for remote access
  shell: cat /home/{{ docker_iam.docker_user }}/.ssh/id_rsa
  register: read_id_rsa
  tags:
    - docker

- name: Print id_rsa for remote access
  debug:
    msg: "SSH Public key for remote access as {{ docker_iam.docker_user }} user {{ read_id_rsa.stdout }}"
  tags:
    - docker
    