---
# Task to manage service state

- name: Enable and start docker service
  service:
    name: docker
    state: started
    enabled: yes
  register: docker_state

- name: Restart docker service if needed
  service:
    name: docker
    state: restarted
  when:
    - docker_state != ""