---

- name: Prepare directory for compose project
  file: 
    path: "{{ compose_project_path }}"
    state: directory
    mode: '0755'
  tags:
    - ci_cd_lab

- name: Copy template
  template:
    src: app.py.j2
    dest: "{{ compose_project_path }}/app.py"
    owner: root
    group: root
    mode: '0744'
  tags:
    - ci_cd_lab
