---

- name: Prepare directory for compose project
  file: 
    path: "{{ compose_project_path }}"
    state: directory
    mode: '0755'
  tags:
    - ci_cd_lab

- name: Copy templates to {{ compose_project_path }}
  template:
    src: "{{ item.path }}"
    dest: "{{ compose_project_path }}/{{ item.path | regex_replace('.j2', '') }}"
    owner: root
    group: root
    mode: '0744'
  with_filetree: "../templates"
  tags:
    - ci_cd_lab
    