---
- hosts: ci_cd_lab
  gather_facts: no
  become: yes

  roles:
    ## INSTALL BASE CONFIG (DOCKER, REPOS ETC)
    - ../roles/manage.common_tasks

    ## MANAGE DOCKER_ENGINE (START / RESTART OR CHANGE CONFIGURATION)
    - ../roles/manage.docker_engine

    ## MANAGE DOCKER_COMPOSE
    - ../roles/manage.docker_compose

    ## START WITH DOCKER_COMPOSE PROJECT
    - ../roles/docker_compose.ci_cd_lab
